services:
    PM\Bundle\LoggerBundle\Services\LogService:
        public: true
        autowire: true
        calls:
            - [setLogger, ['@?logger']]
            - [setRequestStack, [ '@?request_stack']]


    PM\Bundle\LoggerBundle\Twig\LoggerTwigExtension
        calls:
            - [setDoctrine, ['@doctrine']]
        tags:
            - { name: twig.extension }
